### ISSUE TITLE
multiple templates in one file

### ISSUE THREAD

**Issue by ruicsh** [deepsweet/baggage-loader#10]
can baggage-loader work on multiple template files included from one file?

I have multiple directives in the same file, each one with its own templateUrl. I can only have it working on the first template used.

I'm using webpack's ngtemplate-loader as detailed here: https://github.com/WearyMonkey/ngtemplate-loader#baggage-example

myModule.js
`app.directive('myDirectiveA', () => ({
    templateUrl: require('./fileA.template.html')  
  });
app.directive('myDirectiveB', () => ({
    templateUrl: require('./fileB.template.html')  
  });`

**Comment by deepsweet** [comment]
https://github.com/deepsweet/baggage-loader/issues/11
